name: run JBRE OBE tests 

on:
  push:
    branches:
      'feature/*'

jobs:
  run-JBRE-tests:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
    uses: actions/checkout@v4.2.2

    - name: Checkout
      uses: actions/checkout@v3.3.0

      - name: run JBRE tests
        run: mvn test

  
